export enum ConsentEnum {
    EMPLOYMENT_REQUESTS_INITIATION = "EMPLOYMENT_REQUESTS_INITIATION",
    EMPLOYMENT_REQUESTS_ACCEPTANCE = "EMPLOYMENT_REQUESTS_ACCEPTANCE",
    EMPLOYMENT_REQUESTS_RESIGNATION_BY_BUSINESS = "EMPLOYMENT_REQUESTS_RESIGNATION_BY_BUSINESS",
    EMPLOYMENT_REQUESTS_RESIGNATION_BY_EMPLOYEE = "EMPLOYMENT_REQUESTS_RESIGNATION_BY_EMPLOYEE"
}